import {CalendarIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'event',
  title: 'Event',
  icon: CalendarIcon,
  description: 'A public event detail page and listing item.',
  type: 'document',
  groups: [
    {name: 'page', title: 'Page', default: true},
    {name: 'schedule', title: 'Schedule'},
    {name: 'media', title: 'Media'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      description: 'The name of the event.',
      type: 'string',
      group: 'page',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      description: 'The path used for this event in the website URL.',
      type: 'slug',
      group: 'page',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'eventType',
      title: 'Event type',
      description: 'A simple label to help categorize this event.',
      type: 'string',
      group: 'page',
      options: {list: ['public', 'dinner', 'music', 'class']},
    }),
    defineField({
      name: 'venueType',
      title: 'Venue type',
      description: 'Where this event primarily takes place.',
      type: 'string',
      group: 'schedule',
      options: {list: ['restaurant', 'outdoorSpace', 'fullProperty']},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'startDateTime',
      title: 'Start date and time',
      description: 'When the event begins.',
      type: 'datetime',
      group: 'schedule',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'endDateTime',
      title: 'End date and time',
      description: 'When the event ends, if known.',
      type: 'datetime',
      group: 'schedule',
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      description: 'A short summary for listings and the event header.',
      type: 'text',
      rows: 3,
      group: 'page',
    }),
    defineField({
      name: 'body',
      title: 'Body',
      description: 'Longer formatted content for the event detail page.',
      type: 'richTextBlock',
      group: 'page',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      description: 'The main image used for this event.',
      type: 'image',
      options: {hotspot: true},
      fields: [{name: 'alt', title: 'Alternative text', type: 'string'}],
      group: 'media',
    }),
    defineField({
      name: 'link',
      title: 'Link',
      description: 'An optional supporting link for the event detail page.',
      type: 'link',
      group: 'page',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      description: 'The current publishing or availability status of the event.',
      type: 'string',
      group: 'schedule',
      options: {list: ['scheduled', 'soldOut', 'cancelled', 'past']},
      initialValue: 'scheduled',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      description: 'Turn this on to feature the event in curated event lists.',
      type: 'boolean',
      initialValue: false,
      group: 'page',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      description: 'Search and social sharing details for this event.',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      startDateTime: 'startDateTime',
      status: 'status',
      media: 'heroImage',
    },
    prepare({media, startDateTime, status, title}) {
      const parts = [status, startDateTime].filter(Boolean)

      return {
        title: title || 'Event',
        subtitle: parts.join(' • ') || 'No schedule yet',
        media,
      }
    },
  },
})
